"""updated the classes.

Revision ID: b67f74365ac0
Revises: 9d0c25ad18b3
Create Date: 2018-11-20 08:24:19.781368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67f74365ac0'
down_revision = '9d0c25ad18b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    op.drop_column('comments', 'date')
    op.drop_column('comments', 'time')
    op.add_column('pitches', sa.Column('posted', sa.DateTime(), nullable=True))
    op.drop_column('pitches', 'date')
    op.drop_column('pitches', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('time', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('date', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'posted')
    op.add_column('comments', sa.Column('time', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('comments', sa.Column('date', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('comments', 'posted')
    # ### end Alembic commands ###
